title: Scarlet’s Tech Blog
description: Front-end • Product • Design

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false

header_pages:
  - index.md
  - blog.md
  - about.md
  - projects.md
  - contact.md